### ISSUE TITLE
Waf: The wscript in '.../ns-allinone-3.19/ns-3.19' is unreadable

### ISSUE THREAD

**Issue by GaryWang778** [conweave-project/conweave-ns3#1]
I have found several syntax errors in 'wscript' file, like indentation issues or `print "xxx"`.
I wonder if this is the upload version error?

**Comment by GaryWang778** [comment]
I have fixed this problem, thanks.

**Comment by Zyf-01** [comment]
Hello, I would like to ask you how you solved this problem

**Comment by Zyf-01** [comment]
I have fixed this problem
