### ISSUE TITLE
Cannot run :SyntaxError

### ISSUE THREAD

**Issue by hutb2858** [conweave-project/conweave-ns3#3]
File "/../ns-allinone-3.19/ns-3.19/./waf", line 166
    #BZh91AY&SY`|çÿÿÿ¾2tÿÿÿÿÿÿÿÿÿÿÿ
SyntaxError: source code cannot contain null bytes
srun: error: n00174: task 0: Exited with exit code 1

**Comment by iskandar475** [comment]
fixed.

**Comment by hutb2858** [comment]
fixed.
