### ISSUE TITLE
`docker build` fails due to pip package installation error

### ISSUE THREAD

**Issue by y-koj** [conweave-project/conweave-ns3#5]
With the Dockerfile listed in the Readme.md, `docker build` failed with the following error.

```
ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install
```

It was caused by the duplicating pip's `install` subcommand in the Dockerfile:
```
RUN ... && pip3 install install numpy matplotlib cycler
```

and replacing it like below worked for me.
```
RUN ... && pip3 install numpy matplotlib cycler
```

**Comment by ChahwanSong** [comment]
Thanks. I modified the README.md accordingly.
